### ISSUE TITLE
Is there a reason this module requires node >=5

### ISSUE THREAD

**Issue by JetFault** [shellscape/gulp-scan#6]
I was wondering if there is a reason that this plugin is using node >= 5. I'm running 4.5.0 and it's been working fine for me

**Comment by shellscape** [comment]
If I were to test it on 4.x, it'd be 4.7.2. Version 4.5 is pretty far behind at this point even see: http://node.green/. As of this April, the 4x branch exits LTS https://github.com/nodejs/LTS

If it's your company keeping on 4.x, I'd highly suggest pushing them to jump ahead.

If the plugin works on 4.5, then you can still use it. `"engines"` in package.json is not `"engineStrict"` so it should still install.
